config/routes.rb
Rails.application.routes.draw do
  root "tags#index"
  devise_for :users
  resources :sheets do
    resources :tags
  end
  resources :profiles

  resources :sheets_tags

  get "sheets/:id" => "sheets#show"
  get "sheets/new" => 'sheets#new', :as => :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  has_and_belongs_to_many :tags

  belongs_to :user

  validates_presence_of :title, :body, :tag_ids

  def self.search(search)
    where("title ILIKE ? ", "%#{search}%")
  end

  def self.select_owned(current_user_id)
    @ids = [User.find{ |x| x[:email] ==  'admin@test.com' }.id]
    (@ids << current_user_id) if current_user_id
    select{ |i| @ids.include?(i.user_id) }
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :sheets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :sheets

  accepts_nested_attributes_for :profile, :allow_destroy => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit( :email, :password, :password_confirmation, profile_attributes: [ :first_name, :last_name, :avatar, :bio ] )
    end

  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to @profile
    else
      render 'new'
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def destroy
    @profile.destroy
    redirect_to root_path
  end

  private

    def profile_params
      params.require(:profile).permit(:title, :body, :first_name, :last_name, :bio, :avatar )
    end

    def find_profile
      @profile = Profile.find(params[:id])
    end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :find_sheet, only: [:show, :edit, :update, :destroy]
  before_action :check_access
  helper_method :sort_column, :sort_direction

  def index
    if params[:search]
      @sheets = Sheet.search(params[:search]).order(created_at: :desc)
    else
      @sheets = Sheet.select{ |i| @ids.include?(i.user_id) }
      @sheets = @sheets.sort_by{ |sheet| sheet[:created_at]}
    end

    @tags = Tag.order("LOWER(title) asc")
  end

  def show
    @sheets = Sheet.select{ |i| @ids.include?(i.user_id) }

    @sheet = Sheet.find(params[:id])

    if params[:tag].nil?
      @tag = nil
    else
      @tag = Tag.find(params[:tag])
    end

    @tags = Tag.order("LOWER(title) asc")
  end

  def new
    @sheet = Sheet.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @sheet = Sheet.new(sheet_params)

    if @sheet.save
      respond_to do |format|
        format.html { redirect_to sheet_path(@sheet.id) }
        format.js
      end
    else
      render :new
    end
  end

  def update
    @sheet = Sheet.find(params[:id])

    if @sheet.update(sheet_params)
      respond_to do |format|
        format.html {redirect_to sheet_path(@sheet)}
        format.js
      end
    else
      render 'edit'
    end
  end

  def destroy
    @sheet.destroy
    redirect_to root_path, notice: "Sheet was successfully deleted!"
  end

  private

  def sheet_params
    params.require(:sheet).permit(:title, :body, {:tag_ids => []})
  end

  def find_sheet
    @sheet = Sheet.find(params[:id])
  end

  def sortable_columns
  ["created_at"]
  end

  def sort_column
  sortable_columns.include?(params[:column]) ? params[:column] : "created_at"
  end

  def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def check_access
    @ids = [User.find{ |x| x[:email] ==  'admin@test.com' }.id]
    @ids << current_user.id if current_user
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.order("LOWER(title) asc")
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to @tag
    else
      render 'new'
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag
    else
      render 'edit'
    end
  end

  def destroy
    @tag.destroy
    redirect_to root_path
  end

  private

    def tag_params
      params.require(:tag).permit(:title)
    end

    def find_tag
      @tag = Tag.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  class CodeRayify < Redcarpet::Render::HTML
      def block_code(code, language)
        CodeRay.scan(code, language).div
      end
    end

    def markdown(text)
      coderayified = CodeRayify.new(:filter_html => true,
                                    :hard_wrap => true)
      options = {
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :autolink => true,
        :strikethrough => true,
        :lax_html_blocks => true,
        :superscript => true
      }
      markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
      markdown_to_html.render(text).html_safe
    end
    
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
  def sort_link(column, title = nil, tag = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    if !tag.nil?
      link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction, tag: tag[:tag]}
    else
      link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <ul class="nav navbar-nav navbar-left">
          <li>
            <div class="nav_logo"><%= image_tag("codaisseur-logo.svg") %></div>
          </li>
          <li>
            <div class="nav_title"><%= link_to "CHEATSHEETS", root_path %></div>
          </li>
        </ul>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li>
            <%= link_to "Create Sheet", new_sheet_path  %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= render "layouts/flashes" %>
          </li>
          <li class="search-li">
            <%= render "layouts/search" %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= !current_user.profile.nil? ? current_user.profile.full_name : current_user.email %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Account", profile_path(current_user) %>
              </li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign in", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>

app/views/layouts/_search.html.erb
<div class="col-sm-12">
  <div class="input-group">
    <%= form_tag(sheets_path, :method => "get", id: "search-form") do %>

    <div class="input-group search-bar">
      <span class="input-group-addon">
          <i class="glyphicon glyphicon-search"></i>
      </span>
      <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "form-control"%>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheatsheets</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One|Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>

  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Your emailaddress is: <%= current_user.email %>, isn't it?</p>
  <%= link_to "Click here to update your email or password.", edit_user_registration_path %>

  <div class="field">
    <%= f.label "First name" %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label "Last name" %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label "Avatar" %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label "Bio" %><br />
    <%= f.text_field :bio %>
  </div>

  <p>Your emailaddress is: <%= current_user.email %>, isn't it?</p>

  <div class="actions">
    <%= f.submit "Save your profile"%>
  </div>

<% end %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<h1>Tell us more about yourself</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/profiles/show.html.erb
<div class='container'>
<h1>Hello <%= @profile.first_name  %></h1>

<p>This is what we know of you, so far...:</p>
<br />

<div><%= image_tag @profile.avatar_url.to_s %>
<p>Email: <%= @profile.user.email %></p>
<p>First name: <%= @profile.first_name%></p>
<p>Last name: <%= @profile.last_name %></p>
<p>Bio: <%= @profile.bio %></p>

<%= link_to "Edit your profile", edit_profile_path( current_user.profile.id ) %><br />

<%= link_to "Change your password", edit_user_registration_path %><br />

<%= link_to "Delete your user account", edit_user_registration_path %><br />
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/sheets/_form.html.erb
<div class="container">
  <div class="row new-sheet">

    <%= form_for @sheet, class: "form-group" do |f| %>

      <div class="field col-xs-8">


        <div class="pull-right select-column">
          <%= f.collection_select "tag_ids", Tag.all, :id, :title,
          { include_blank: false }, {multiple: true } %>
        </div>

        <div class="col-xs-8">
          <%= f.text_field :title, class: "form-control", placeholder: "What's the title of this cheatsheet?" %>
        </div>

        <div class="col-xs-8">
          <%= f.text_area :body, class: "form-control", size: "40x15", placeholder: "Type your cheat here...." %>
        </div>

        <div class="col-xs-8 text-right">
         <%= link_to 'Cancel', root_path, class: 'btn btn-default'  %>
         <%= f.submit "Create", class: "btn" %>
        </div>

      </div>

    <% end %>

  </div>
</div>

app/views/sheets/_index.html.erb
<div class="partial tags-show-partial">
  <div class="tags-show-partial-head">
  </div>

  <% @sheets.each do |sheet| %>
      <% if sheet == selected_sheet %>
        <div class="tags-show-partial-element selected">
          <h4><%= sheet.title %></h4>
        </div>
      <% else %>
        <div class="tags-show-partial-element">
          <h4><%= link_to sheet.title, { controller: 'sheets', action: 'show', id: sheet.id } %></h4>
        </div>
      <% end %>
  <% end %>
</div>

app/views/sheets/_show.html.erb
<div id="sheet-<%= sheet.id %>" class="sheet-body">
  <div class="partial sheets-show-partial">
    <% if user_signed_in? %>
      <%= link_to sheet_path(sheet), method: :delete, data: { confirm: "Are you sure to delete this sheet?" } do %><i class="link_tool fa fa-trash-o" href="#"></i><% end %>

      <div class="link_tool fa fa-star-o"></div>

      <a id="<%= sheet.id %>" class="edit-btn-sheet" href="#">
        <i class="link_tool fa fa-pencil"></i>
      </a>
    <% end %>

    <h3 class="sheet-title"><%= sheet.title %></h3>

    <div  class="sheet-tags">
      <% sheet.tags.each do |tag| %>
        <i><%= tag.title %></i>
      <% end %>
    </div>
    <div><%= markdown(sheet.body) %></div>
  </div>
</div>

<div id="form-<%= sheet.id %>" class="edit-sheet-form hidden">

  <%= form_for sheet, class: "form-group" do |f| %>
      <div id="tags-<%= sheet.id %>" class="edit-tags">
        <%= f.collection_select "tag_ids", Tag.all, :id, :title,
        { include_blank: false }, {multiple: true } %>
      </div>
      <div id="title-<%= sheet.id %>" class="edit-title">
        <%= f.text_field :title, class: "form-control", placeholder: "What's the title of this cheatsheet?" %>
      </div>
      <div id="body-<%= sheet.id %>" class='edit-body'>
      <%= f.text_area :body, class: "form-control", size: '40x15', placeholder: "Type your cheat here...." %>
      </div>

    <div class="col-xs-8 text-right">
     <%= link_to 'Cancel', root_path, class: 'btn btn-default' %>
    </div>
    <button sheet_id="<%= sheet.id %>" class="btn pull-right save-edit">Save edit</button>
  <% end %>
</div>

app/views/sheets/create.html.erb
<h1>Sheets#create</h1>
<p>Find me in app/views/sheets/create.html.erb</p>

app/views/sheets/destroy.html.erb
<h1>Sheets#destroy</h1>
<p>Find me in app/views/sheets/destroy.html.erb</p>

app/views/sheets/index.html.erb
<div class="row">
  <div class="col col-xs-12 col-sm-5 col-md-2 block_left">
    <%= render partial: "tags/index", locals: { tags: @tags, selected_tag: nil } %>
  </div>
  <div class="col col-xs-12 col-sm-7 col-md-3 block_centre">
    <%= render partial: "sheets/index", locals: { sheets: @sheets, selected_sheet: @sheets.first || nil } %>
  </div>
  <div class="col col-xs-12 col-sm-12 col-md-7 block_right">
    <% if @sheets.first != nil %>
      <%= render partial: "sheets/show", locals: { sheet: @sheets.first || nil } %>
    <% end %>
  </div>
</div>

app/views/sheets/new.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/sheets/show.html.erb
<div class="row">
  <div class="col col-xs-12 col-sm-5 col-md-2 block_left">
    <%= render partial: "tags/index", locals: { tags: @tags, selected_tag: (@tag || @sheet.tags.first) } %>
  </div>
  <div class="col col-xs-12 col-sm-7 col-md-3 block_centre">
    <%= render partial: "tags/show", locals: { tag: (@tag || @sheet.tags.first), selected_sheet: @sheet } %>
  </div>
  <div class="col col-xs-12 col-sm-12 col-md-7 block_right">
    <%= render partial: "sheets/show", locals: { sheet: @sheet } %>
  </div>
</div>

app/views/sheets/update.html.erb
<h1>Sheets#update</h1>
<p>Find me in app/views/sheets/update.html.erb</p>

app/views/tags/_index.html.erb
<div class="partial tags_index_partial">
  <ul class="tag-list" style="list-style-type: none;">
    <% tags.each do |tag| %>
      <% if tag.sheets.length != 0 %>
        <li>
          <div class='<%= tag.div_class ? tag.div_class : tag.fallback_icon %> tag_icon_partial'></div>
          <div class='tag_title_partial'>
            <% if tag == selected_tag %>
              <%= tag.title %>
            <% else %>
              <%= link_to tag.title, { controller: 'sheets', action: 'show', id: tag.sheets.first.id, tag: tag.id } %>
            <% end %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/tags/_show.html.erb
<div class="partial tags-show-partial">
  <div class="tags-show-partial-head">
    <ul class="list-inline">
      <li class="active"><%= sort_link "created_at", "Sort by date", tag: tag.id %></li>
    </ul>
  </div>
  <% selection = tag.sheets.order("#{params[:column]} #{params[:direction]}") %>
  <% if selection != [] %>
    <% selection.each do |sheet|  %>
      <% if sheet == selected_sheet %>
        <div class="tags-show-partial-element selected">
          <h4><%= sheet.title %></h4>
        </div>
      <% else %>
        <div class="tags-show-partial-element">
          <h4><%= link_to sheet.title, { controller: 'sheets', action: 'show', id: sheet.id, tag: tag.id } %></h4>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tags/_tag.html.erb
<% if tag.sheets.length != 0 %>
  <div class="tag_button col-md-6">
    <div class='<%= tag.div_class ? tag.div_class : fallback_icon %> col-md-1 tag_icon'></div>
    <div class='tag_title col-md-5'>
      <%= link_to tag.title, { controller: 'sheets', action: 'show', id: tag.sheets.first.id, tag: tag.id } %>
    </div>
  </div>
<% end %>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/index.html.erb
<div class="row">
  <div class='block_tags_overview col-md-12'>
    <%= render @tags %>
  </div>

  <div class='block_read_items col-md-6'>
    <div class="head_item_tag">Most used cheatsheets</div>
    <div class="read_item">Facillimum id quidem est, inquam.</div>
    <div class="read_item">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
    <div class="read_item">Estne, quaeso, inquam, sitienti in bibendo voluptas?</div>
    <div class="read_item">Facillimum id quidem est, inquam.</div>
  </div>

  <div class="block_read_items col-md-6">
    <div class="head_item_tag">Latest cheatsheets</div>
    <div class="read_item">Facillimum id quidem est, inquam.</div>
    <div class="read_item">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
    <div class="read_item">Proclivi currit oratio?</div>
  </div>
</div>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>